FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
		libfreetype-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
		libzip-dev \
		supervisor \
		cron \
	&& docker-php-ext-install -j$(nproc) pdo pdo_mysql zip pcntl \
	&& rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
COPY ./entrypoint.sh /usr/local/bin
COPY ./supervisord.conf /etc/supervisor/supervisord.conf
COPY ./crontab /etc/cron.d/buildovate-cron

RUN chmod 0644 /etc/cron.d/buildovate-cron \
	&& crontab /etc/cron.d/buildovate-cron
RUN chmod +x /usr/local/bin/entrypoint.sh

CMD ["/usr/local/bin/entrypoint.sh"]
